/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as BookRouteImport } from './routes/book'
import { Route as BookingConfirmedRouteImport } from './routes/booking-confirmed'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as WorkerLoginRouteImport } from './routes/worker.login'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin/bookings'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminWorkersRouteImport } from './routes/_authenticated/admin/workers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmedRoute = BookingConfirmedRouteImport.update({
  id: '/booking-confirmed',
  path: '/booking-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerLoginRoute = WorkerLoginRouteImport.update({
  id: '/worker/login',
  path: '/worker/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminWorkersRoute =
  AuthenticatedAdminWorkersRouteImport.update({
    id: '/workers',
    path: '/workers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/service-areas': typeof ServiceAreasRoute
  '/services': typeof ServicesRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/worker/login': typeof WorkerLoginRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/workers': typeof AuthenticatedAdminWorkersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/service-areas': typeof ServiceAreasRoute
  '/services': typeof ServicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/worker/login': typeof WorkerLoginRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/workers': typeof AuthenticatedAdminWorkersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/book': typeof BookRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/service-areas': typeof ServiceAreasRoute
  '/services': typeof ServicesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/worker/login': typeof WorkerLoginRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/workers': typeof AuthenticatedAdminWorkersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/booking-confirmed'
    | '/how-it-works'
    | '/service-areas'
    | '/services'
    | '/admin'
    | '/admin/login'
    | '/worker/login'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/workers'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/booking-confirmed'
    | '/how-it-works'
    | '/service-areas'
    | '/services'
    | '/admin/login'
    | '/worker/login'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/workers'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/book'
    | '/booking-confirmed'
    | '/how-it-works'
    | '/service-areas'
    | '/services'
    | '/_authenticated/admin'
    | '/admin/login'
    | '/worker/login'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/workers'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BookRoute: typeof BookRoute
  BookingConfirmedRoute: typeof BookingConfirmedRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ServiceAreasRoute: typeof ServiceAreasRoute
  ServicesRoute: typeof ServicesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  WorkerLoginRoute: typeof WorkerLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmed': {
      id: '/booking-confirmed'
      path: '/booking-confirmed'
      fullPath: '/booking-confirmed'
      preLoaderRoute: typeof BookingConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/login': {
      id: '/worker/login'
      path: '/worker/login'
      fullPath: '/worker/login'
      preLoaderRoute: typeof WorkerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/workers': {
      id: '/_authenticated/admin/workers'
      path: '/workers'
      fullPath: '/admin/workers'
      preLoaderRoute: typeof AuthenticatedAdminWorkersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminWorkersRoute: typeof AuthenticatedAdminWorkersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminWorkersRoute: AuthenticatedAdminWorkersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BookRoute: BookRoute,
  BookingConfirmedRoute: BookingConfirmedRoute,
  HowItWorksRoute: HowItWorksRoute,
  ServiceAreasRoute: ServiceAreasRoute,
  ServicesRoute: ServicesRoute,
  AdminLoginRoute: AdminLoginRoute,
  WorkerLoginRoute: WorkerLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
